### ISSUE TITLE
Clean-up, moving to this repo for continuing development

### ISSUE THREAD

**Issue by dereklieu** [developmentseed/sensor-rest-api#1]
@scisco @smit1678 

Getting to the point where I can push my work on this API app up here. It currently returns average readings for an arbitrary # of hours. You can also query this data for a specific username, which will correspond to sensors.

Need to do before I push it up here:

- [ ] Return one average reading for each hour requested. Currently gives one average reading for all the hours requested.
- [ ] Return average reading for all active sensors, or users, for the last hour.

Once I push it up here, the plan is to run the app on the iMac we have in the office and point our own sensors to it so we can start recording actual data. This will work for testing and continuing development.

**Comment by scisco** [comment]
Closing as it is no longer relevant.
