### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by kamicut** [developmentseed/sensor-rest-api#6]
We need to document the endpoints that are served by the API, as well as the actions an authenticated user can do on the web browsable interface. Would the documentation be part of the frontend? 

Currently, the endpoint is (in optargs notation):

`/readings/[aggregate/]?format=json[&users=user1,user2,..][&start_date=yyyy-mm-dd]`

- Adding `/aggregate/` will aggregate by hour. 
- `start_date` restricts by record creation date after a certain date
- `users` filters by owner of the record

cc @dereklieu

**Comment by scisco** [comment]
Done here: http://docs.sensorrestapi.apiary.io/#reference/undefined
